// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

package com.example.elements;

public final class BlockInfo {
  private BlockInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HDFS.Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 num = 1;</code>
     */
    boolean hasNum();
    /**
     * <code>required int32 num = 1;</code>
     */
    int getNum();

    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    java.util.List<com.example.elements.DataNodeInfo.DataNode> 
        getDataNodeList();
    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    com.example.elements.DataNodeInfo.DataNode getDataNode(int index);
    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    int getDataNodeCount();
    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    java.util.List<? extends com.example.elements.DataNodeInfo.DataNodeOrBuilder> 
        getDataNodeOrBuilderList();
    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    com.example.elements.DataNodeInfo.DataNodeOrBuilder getDataNodeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HDFS.Block}
   */
  public  static final class Block extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HDFS.Block)
      BlockOrBuilder {
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Block() {
      num_ = 0;
      dataNode_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              num_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                dataNode_ = new java.util.ArrayList<com.example.elements.DataNodeInfo.DataNode>();
                mutable_bitField0_ |= 0x00000002;
              }
              dataNode_.add(
                  input.readMessage(com.example.elements.DataNodeInfo.DataNode.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          dataNode_ = java.util.Collections.unmodifiableList(dataNode_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.elements.BlockInfo.internal_static_HDFS_Block_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.elements.BlockInfo.internal_static_HDFS_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.elements.BlockInfo.Block.class, com.example.elements.BlockInfo.Block.Builder.class);
    }

    private int bitField0_;
    public static final int NUM_FIELD_NUMBER = 1;
    private int num_;
    /**
     * <code>required int32 num = 1;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 num = 1;</code>
     */
    public int getNum() {
      return num_;
    }

    public static final int DATANODE_FIELD_NUMBER = 2;
    private java.util.List<com.example.elements.DataNodeInfo.DataNode> dataNode_;
    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    public java.util.List<com.example.elements.DataNodeInfo.DataNode> getDataNodeList() {
      return dataNode_;
    }
    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    public java.util.List<? extends com.example.elements.DataNodeInfo.DataNodeOrBuilder> 
        getDataNodeOrBuilderList() {
      return dataNode_;
    }
    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    public int getDataNodeCount() {
      return dataNode_.size();
    }
    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    public com.example.elements.DataNodeInfo.DataNode getDataNode(int index) {
      return dataNode_.get(index);
    }
    /**
     * <code>repeated .HDFS.DataNode dataNode = 2;</code>
     */
    public com.example.elements.DataNodeInfo.DataNodeOrBuilder getDataNodeOrBuilder(
        int index) {
      return dataNode_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDataNodeCount(); i++) {
        if (!getDataNode(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, num_);
      }
      for (int i = 0; i < dataNode_.size(); i++) {
        output.writeMessage(2, dataNode_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num_);
      }
      for (int i = 0; i < dataNode_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, dataNode_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.elements.BlockInfo.Block)) {
        return super.equals(obj);
      }
      com.example.elements.BlockInfo.Block other = (com.example.elements.BlockInfo.Block) obj;

      boolean result = true;
      result = result && (hasNum() == other.hasNum());
      if (hasNum()) {
        result = result && (getNum()
            == other.getNum());
      }
      result = result && getDataNodeList()
          .equals(other.getDataNodeList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNum()) {
        hash = (37 * hash) + NUM_FIELD_NUMBER;
        hash = (53 * hash) + getNum();
      }
      if (getDataNodeCount() > 0) {
        hash = (37 * hash) + DATANODE_FIELD_NUMBER;
        hash = (53 * hash) + getDataNodeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.elements.BlockInfo.Block parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.elements.BlockInfo.Block parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.elements.BlockInfo.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.elements.BlockInfo.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.elements.BlockInfo.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.elements.BlockInfo.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.elements.BlockInfo.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.elements.BlockInfo.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.elements.BlockInfo.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.elements.BlockInfo.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.elements.BlockInfo.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.elements.BlockInfo.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.elements.BlockInfo.Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HDFS.Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HDFS.Block)
        com.example.elements.BlockInfo.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.elements.BlockInfo.internal_static_HDFS_Block_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.elements.BlockInfo.internal_static_HDFS_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.elements.BlockInfo.Block.class, com.example.elements.BlockInfo.Block.Builder.class);
      }

      // Construct using com.example.elements.BlockInfo.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataNodeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (dataNodeBuilder_ == null) {
          dataNode_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          dataNodeBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.elements.BlockInfo.internal_static_HDFS_Block_descriptor;
      }

      public com.example.elements.BlockInfo.Block getDefaultInstanceForType() {
        return com.example.elements.BlockInfo.Block.getDefaultInstance();
      }

      public com.example.elements.BlockInfo.Block build() {
        com.example.elements.BlockInfo.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.elements.BlockInfo.Block buildPartial() {
        com.example.elements.BlockInfo.Block result = new com.example.elements.BlockInfo.Block(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.num_ = num_;
        if (dataNodeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            dataNode_ = java.util.Collections.unmodifiableList(dataNode_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.dataNode_ = dataNode_;
        } else {
          result.dataNode_ = dataNodeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.elements.BlockInfo.Block) {
          return mergeFrom((com.example.elements.BlockInfo.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.elements.BlockInfo.Block other) {
        if (other == com.example.elements.BlockInfo.Block.getDefaultInstance()) return this;
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        if (dataNodeBuilder_ == null) {
          if (!other.dataNode_.isEmpty()) {
            if (dataNode_.isEmpty()) {
              dataNode_ = other.dataNode_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDataNodeIsMutable();
              dataNode_.addAll(other.dataNode_);
            }
            onChanged();
          }
        } else {
          if (!other.dataNode_.isEmpty()) {
            if (dataNodeBuilder_.isEmpty()) {
              dataNodeBuilder_.dispose();
              dataNodeBuilder_ = null;
              dataNode_ = other.dataNode_;
              bitField0_ = (bitField0_ & ~0x00000002);
              dataNodeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataNodeFieldBuilder() : null;
            } else {
              dataNodeBuilder_.addAllMessages(other.dataNode_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNum()) {
          return false;
        }
        for (int i = 0; i < getDataNodeCount(); i++) {
          if (!getDataNode(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.elements.BlockInfo.Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.elements.BlockInfo.Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int num_ ;
      /**
       * <code>required int32 num = 1;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 num = 1;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required int32 num = 1;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000001;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num = 1;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.example.elements.DataNodeInfo.DataNode> dataNode_ =
        java.util.Collections.emptyList();
      private void ensureDataNodeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          dataNode_ = new java.util.ArrayList<com.example.elements.DataNodeInfo.DataNode>(dataNode_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.elements.DataNodeInfo.DataNode, com.example.elements.DataNodeInfo.DataNode.Builder, com.example.elements.DataNodeInfo.DataNodeOrBuilder> dataNodeBuilder_;

      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public java.util.List<com.example.elements.DataNodeInfo.DataNode> getDataNodeList() {
        if (dataNodeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dataNode_);
        } else {
          return dataNodeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public int getDataNodeCount() {
        if (dataNodeBuilder_ == null) {
          return dataNode_.size();
        } else {
          return dataNodeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public com.example.elements.DataNodeInfo.DataNode getDataNode(int index) {
        if (dataNodeBuilder_ == null) {
          return dataNode_.get(index);
        } else {
          return dataNodeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public Builder setDataNode(
          int index, com.example.elements.DataNodeInfo.DataNode value) {
        if (dataNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataNodeIsMutable();
          dataNode_.set(index, value);
          onChanged();
        } else {
          dataNodeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public Builder setDataNode(
          int index, com.example.elements.DataNodeInfo.DataNode.Builder builderForValue) {
        if (dataNodeBuilder_ == null) {
          ensureDataNodeIsMutable();
          dataNode_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataNodeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public Builder addDataNode(com.example.elements.DataNodeInfo.DataNode value) {
        if (dataNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataNodeIsMutable();
          dataNode_.add(value);
          onChanged();
        } else {
          dataNodeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public Builder addDataNode(
          int index, com.example.elements.DataNodeInfo.DataNode value) {
        if (dataNodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataNodeIsMutable();
          dataNode_.add(index, value);
          onChanged();
        } else {
          dataNodeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public Builder addDataNode(
          com.example.elements.DataNodeInfo.DataNode.Builder builderForValue) {
        if (dataNodeBuilder_ == null) {
          ensureDataNodeIsMutable();
          dataNode_.add(builderForValue.build());
          onChanged();
        } else {
          dataNodeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public Builder addDataNode(
          int index, com.example.elements.DataNodeInfo.DataNode.Builder builderForValue) {
        if (dataNodeBuilder_ == null) {
          ensureDataNodeIsMutable();
          dataNode_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataNodeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public Builder addAllDataNode(
          java.lang.Iterable<? extends com.example.elements.DataNodeInfo.DataNode> values) {
        if (dataNodeBuilder_ == null) {
          ensureDataNodeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dataNode_);
          onChanged();
        } else {
          dataNodeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public Builder clearDataNode() {
        if (dataNodeBuilder_ == null) {
          dataNode_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          dataNodeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public Builder removeDataNode(int index) {
        if (dataNodeBuilder_ == null) {
          ensureDataNodeIsMutable();
          dataNode_.remove(index);
          onChanged();
        } else {
          dataNodeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public com.example.elements.DataNodeInfo.DataNode.Builder getDataNodeBuilder(
          int index) {
        return getDataNodeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public com.example.elements.DataNodeInfo.DataNodeOrBuilder getDataNodeOrBuilder(
          int index) {
        if (dataNodeBuilder_ == null) {
          return dataNode_.get(index);  } else {
          return dataNodeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public java.util.List<? extends com.example.elements.DataNodeInfo.DataNodeOrBuilder> 
           getDataNodeOrBuilderList() {
        if (dataNodeBuilder_ != null) {
          return dataNodeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dataNode_);
        }
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public com.example.elements.DataNodeInfo.DataNode.Builder addDataNodeBuilder() {
        return getDataNodeFieldBuilder().addBuilder(
            com.example.elements.DataNodeInfo.DataNode.getDefaultInstance());
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public com.example.elements.DataNodeInfo.DataNode.Builder addDataNodeBuilder(
          int index) {
        return getDataNodeFieldBuilder().addBuilder(
            index, com.example.elements.DataNodeInfo.DataNode.getDefaultInstance());
      }
      /**
       * <code>repeated .HDFS.DataNode dataNode = 2;</code>
       */
      public java.util.List<com.example.elements.DataNodeInfo.DataNode.Builder> 
           getDataNodeBuilderList() {
        return getDataNodeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.elements.DataNodeInfo.DataNode, com.example.elements.DataNodeInfo.DataNode.Builder, com.example.elements.DataNodeInfo.DataNodeOrBuilder> 
          getDataNodeFieldBuilder() {
        if (dataNodeBuilder_ == null) {
          dataNodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.elements.DataNodeInfo.DataNode, com.example.elements.DataNodeInfo.DataNode.Builder, com.example.elements.DataNodeInfo.DataNodeOrBuilder>(
                  dataNode_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          dataNode_ = null;
        }
        return dataNodeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HDFS.Block)
    }

    // @@protoc_insertion_point(class_scope:HDFS.Block)
    private static final com.example.elements.BlockInfo.Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.elements.BlockInfo.Block();
    }

    public static com.example.elements.BlockInfo.Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    public com.example.elements.BlockInfo.Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HDFS_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HDFS_Block_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Block.proto\022\004HDFS\032\016DataNode.proto\"6\n\005B" +
      "lock\022\013\n\003num\030\001 \002(\005\022 \n\010dataNode\030\002 \003(\0132\016.HD" +
      "FS.DataNodeB!\n\024com.example.elementsB\tBlo" +
      "ckInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.elements.DataNodeInfo.getDescriptor(),
        }, assigner);
    internal_static_HDFS_Block_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HDFS_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HDFS_Block_descriptor,
        new java.lang.String[] { "Num", "DataNode", });
    com.example.elements.DataNodeInfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
