// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Directory.proto

package com.example.elements;

public final class DirectoryInfo {
  private DirectoryInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HDFS.File)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string fileName = 1;</code>
     */
    boolean hasFileName();
    /**
     * <code>required string fileName = 1;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>required string fileName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional string timeStamp = 2;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    java.lang.String getTimeStamp();
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>optional int32 size = 3;</code>
     */
    boolean hasSize();
    /**
     * <code>optional int32 size = 3;</code>
     */
    int getSize();
  }
  /**
   * Protobuf type {@code HDFS.File}
   */
  public  static final class File extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HDFS.File)
      FileOrBuilder {
    // Use File.newBuilder() to construct.
    private File(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private File() {
      fileName_ = "";
      timeStamp_ = "";
      size_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private File(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fileName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              timeStamp_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              size_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.elements.DirectoryInfo.internal_static_HDFS_File_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.elements.DirectoryInfo.internal_static_HDFS_File_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.elements.DirectoryInfo.File.class, com.example.elements.DirectoryInfo.File.Builder.class);
    }

    private int bitField0_;
    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fileName_;
    /**
     * <code>required string fileName = 1;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fileName = 1;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timeStamp_;
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeStamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    /**
     * <code>optional int32 size = 3;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 size = 3;</code>
     */
    public int getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFileName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeStamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, size_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeStamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, size_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.elements.DirectoryInfo.File)) {
        return super.equals(obj);
      }
      com.example.elements.DirectoryInfo.File other = (com.example.elements.DirectoryInfo.File) obj;

      boolean result = true;
      result = result && (hasFileName() == other.hasFileName());
      if (hasFileName()) {
        result = result && getFileName()
            .equals(other.getFileName());
      }
      result = result && (hasTimeStamp() == other.hasTimeStamp());
      if (hasTimeStamp()) {
        result = result && getTimeStamp()
            .equals(other.getTimeStamp());
      }
      result = result && (hasSize() == other.hasSize());
      if (hasSize()) {
        result = result && (getSize()
            == other.getSize());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFileName()) {
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFileName().hashCode();
      }
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimeStamp().hashCode();
      }
      if (hasSize()) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSize();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.elements.DirectoryInfo.File parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.elements.DirectoryInfo.File parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.File parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.elements.DirectoryInfo.File parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.File parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.elements.DirectoryInfo.File parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.File parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.elements.DirectoryInfo.File parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.File parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.elements.DirectoryInfo.File parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.File parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.elements.DirectoryInfo.File parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.elements.DirectoryInfo.File prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HDFS.File}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HDFS.File)
        com.example.elements.DirectoryInfo.FileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.elements.DirectoryInfo.internal_static_HDFS_File_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.elements.DirectoryInfo.internal_static_HDFS_File_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.elements.DirectoryInfo.File.class, com.example.elements.DirectoryInfo.File.Builder.class);
      }

      // Construct using com.example.elements.DirectoryInfo.File.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timeStamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.elements.DirectoryInfo.internal_static_HDFS_File_descriptor;
      }

      public com.example.elements.DirectoryInfo.File getDefaultInstanceForType() {
        return com.example.elements.DirectoryInfo.File.getDefaultInstance();
      }

      public com.example.elements.DirectoryInfo.File build() {
        com.example.elements.DirectoryInfo.File result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.elements.DirectoryInfo.File buildPartial() {
        com.example.elements.DirectoryInfo.File result = new com.example.elements.DirectoryInfo.File(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.elements.DirectoryInfo.File) {
          return mergeFrom((com.example.elements.DirectoryInfo.File)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.elements.DirectoryInfo.File other) {
        if (other == com.example.elements.DirectoryInfo.File.getDefaultInstance()) return this;
        if (other.hasFileName()) {
          bitField0_ |= 0x00000001;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasTimeStamp()) {
          bitField0_ |= 0x00000002;
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFileName()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.elements.DirectoryInfo.File parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.elements.DirectoryInfo.File) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileName_ = "";
      /**
       * <code>required string fileName = 1;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fileName = 1;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fileName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileName = 1;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 1;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 1;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timeStamp_ = "";
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public java.lang.String getTimeStamp() {
        java.lang.Object ref = timeStamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timeStamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        java.lang.Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public Builder setTimeStamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>optional int32 size = 3;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 size = 3;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>optional int32 size = 3;</code>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000004;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 size = 3;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HDFS.File)
    }

    // @@protoc_insertion_point(class_scope:HDFS.File)
    private static final com.example.elements.DirectoryInfo.File DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.elements.DirectoryInfo.File();
    }

    public static com.example.elements.DirectoryInfo.File getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<File>
        PARSER = new com.google.protobuf.AbstractParser<File>() {
      public File parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new File(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<File> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<File> getParserForType() {
      return PARSER;
    }

    public com.example.elements.DirectoryInfo.File getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DirectoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HDFS.Directory)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string dirName = 1;</code>
     */
    boolean hasDirName();
    /**
     * <code>required string dirName = 1;</code>
     */
    java.lang.String getDirName();
    /**
     * <code>required string dirName = 1;</code>
     */
    com.google.protobuf.ByteString
        getDirNameBytes();

    /**
     * <code>optional string timeStamp = 2;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    java.lang.String getTimeStamp();
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    java.util.List<com.example.elements.DirectoryInfo.Directory> 
        getDirListList();
    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    com.example.elements.DirectoryInfo.Directory getDirList(int index);
    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    int getDirListCount();
    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    java.util.List<? extends com.example.elements.DirectoryInfo.DirectoryOrBuilder> 
        getDirListOrBuilderList();
    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    com.example.elements.DirectoryInfo.DirectoryOrBuilder getDirListOrBuilder(
        int index);

    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    java.util.List<com.example.elements.DirectoryInfo.File> 
        getFileListList();
    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    com.example.elements.DirectoryInfo.File getFileList(int index);
    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    int getFileListCount();
    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    java.util.List<? extends com.example.elements.DirectoryInfo.FileOrBuilder> 
        getFileListOrBuilderList();
    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    com.example.elements.DirectoryInfo.FileOrBuilder getFileListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HDFS.Directory}
   */
  public  static final class Directory extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HDFS.Directory)
      DirectoryOrBuilder {
    // Use Directory.newBuilder() to construct.
    private Directory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Directory() {
      dirName_ = "";
      timeStamp_ = "";
      dirList_ = java.util.Collections.emptyList();
      fileList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Directory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              dirName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              timeStamp_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                dirList_ = new java.util.ArrayList<com.example.elements.DirectoryInfo.Directory>();
                mutable_bitField0_ |= 0x00000004;
              }
              dirList_.add(
                  input.readMessage(com.example.elements.DirectoryInfo.Directory.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                fileList_ = new java.util.ArrayList<com.example.elements.DirectoryInfo.File>();
                mutable_bitField0_ |= 0x00000008;
              }
              fileList_.add(
                  input.readMessage(com.example.elements.DirectoryInfo.File.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          dirList_ = java.util.Collections.unmodifiableList(dirList_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          fileList_ = java.util.Collections.unmodifiableList(fileList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.elements.DirectoryInfo.internal_static_HDFS_Directory_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.elements.DirectoryInfo.internal_static_HDFS_Directory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.elements.DirectoryInfo.Directory.class, com.example.elements.DirectoryInfo.Directory.Builder.class);
    }

    private int bitField0_;
    public static final int DIRNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object dirName_;
    /**
     * <code>required string dirName = 1;</code>
     */
    public boolean hasDirName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string dirName = 1;</code>
     */
    public java.lang.String getDirName() {
      java.lang.Object ref = dirName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dirName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dirName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDirNameBytes() {
      java.lang.Object ref = dirName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dirName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timeStamp_;
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeStamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string timeStamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRLIST_FIELD_NUMBER = 3;
    private java.util.List<com.example.elements.DirectoryInfo.Directory> dirList_;
    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    public java.util.List<com.example.elements.DirectoryInfo.Directory> getDirListList() {
      return dirList_;
    }
    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    public java.util.List<? extends com.example.elements.DirectoryInfo.DirectoryOrBuilder> 
        getDirListOrBuilderList() {
      return dirList_;
    }
    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    public int getDirListCount() {
      return dirList_.size();
    }
    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    public com.example.elements.DirectoryInfo.Directory getDirList(int index) {
      return dirList_.get(index);
    }
    /**
     * <code>repeated .HDFS.Directory dirList = 3;</code>
     */
    public com.example.elements.DirectoryInfo.DirectoryOrBuilder getDirListOrBuilder(
        int index) {
      return dirList_.get(index);
    }

    public static final int FILELIST_FIELD_NUMBER = 4;
    private java.util.List<com.example.elements.DirectoryInfo.File> fileList_;
    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    public java.util.List<com.example.elements.DirectoryInfo.File> getFileListList() {
      return fileList_;
    }
    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    public java.util.List<? extends com.example.elements.DirectoryInfo.FileOrBuilder> 
        getFileListOrBuilderList() {
      return fileList_;
    }
    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    public int getFileListCount() {
      return fileList_.size();
    }
    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    public com.example.elements.DirectoryInfo.File getFileList(int index) {
      return fileList_.get(index);
    }
    /**
     * <code>repeated .HDFS.File fileList = 4;</code>
     */
    public com.example.elements.DirectoryInfo.FileOrBuilder getFileListOrBuilder(
        int index) {
      return fileList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDirName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDirListCount(); i++) {
        if (!getDirList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getFileListCount(); i++) {
        if (!getFileList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dirName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeStamp_);
      }
      for (int i = 0; i < dirList_.size(); i++) {
        output.writeMessage(3, dirList_.get(i));
      }
      for (int i = 0; i < fileList_.size(); i++) {
        output.writeMessage(4, fileList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dirName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeStamp_);
      }
      for (int i = 0; i < dirList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, dirList_.get(i));
      }
      for (int i = 0; i < fileList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, fileList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.elements.DirectoryInfo.Directory)) {
        return super.equals(obj);
      }
      com.example.elements.DirectoryInfo.Directory other = (com.example.elements.DirectoryInfo.Directory) obj;

      boolean result = true;
      result = result && (hasDirName() == other.hasDirName());
      if (hasDirName()) {
        result = result && getDirName()
            .equals(other.getDirName());
      }
      result = result && (hasTimeStamp() == other.hasTimeStamp());
      if (hasTimeStamp()) {
        result = result && getTimeStamp()
            .equals(other.getTimeStamp());
      }
      result = result && getDirListList()
          .equals(other.getDirListList());
      result = result && getFileListList()
          .equals(other.getFileListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDirName()) {
        hash = (37 * hash) + DIRNAME_FIELD_NUMBER;
        hash = (53 * hash) + getDirName().hashCode();
      }
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimeStamp().hashCode();
      }
      if (getDirListCount() > 0) {
        hash = (37 * hash) + DIRLIST_FIELD_NUMBER;
        hash = (53 * hash) + getDirListList().hashCode();
      }
      if (getFileListCount() > 0) {
        hash = (37 * hash) + FILELIST_FIELD_NUMBER;
        hash = (53 * hash) + getFileListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.elements.DirectoryInfo.Directory parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.elements.DirectoryInfo.Directory parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.Directory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.elements.DirectoryInfo.Directory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.Directory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.elements.DirectoryInfo.Directory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.Directory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.elements.DirectoryInfo.Directory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.Directory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.elements.DirectoryInfo.Directory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.elements.DirectoryInfo.Directory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.elements.DirectoryInfo.Directory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.elements.DirectoryInfo.Directory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HDFS.Directory}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HDFS.Directory)
        com.example.elements.DirectoryInfo.DirectoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.elements.DirectoryInfo.internal_static_HDFS_Directory_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.elements.DirectoryInfo.internal_static_HDFS_Directory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.elements.DirectoryInfo.Directory.class, com.example.elements.DirectoryInfo.Directory.Builder.class);
      }

      // Construct using com.example.elements.DirectoryInfo.Directory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDirListFieldBuilder();
          getFileListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        dirName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timeStamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (dirListBuilder_ == null) {
          dirList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          dirListBuilder_.clear();
        }
        if (fileListBuilder_ == null) {
          fileList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          fileListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.elements.DirectoryInfo.internal_static_HDFS_Directory_descriptor;
      }

      public com.example.elements.DirectoryInfo.Directory getDefaultInstanceForType() {
        return com.example.elements.DirectoryInfo.Directory.getDefaultInstance();
      }

      public com.example.elements.DirectoryInfo.Directory build() {
        com.example.elements.DirectoryInfo.Directory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.elements.DirectoryInfo.Directory buildPartial() {
        com.example.elements.DirectoryInfo.Directory result = new com.example.elements.DirectoryInfo.Directory(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dirName_ = dirName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timeStamp_ = timeStamp_;
        if (dirListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            dirList_ = java.util.Collections.unmodifiableList(dirList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.dirList_ = dirList_;
        } else {
          result.dirList_ = dirListBuilder_.build();
        }
        if (fileListBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            fileList_ = java.util.Collections.unmodifiableList(fileList_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.fileList_ = fileList_;
        } else {
          result.fileList_ = fileListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.elements.DirectoryInfo.Directory) {
          return mergeFrom((com.example.elements.DirectoryInfo.Directory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.elements.DirectoryInfo.Directory other) {
        if (other == com.example.elements.DirectoryInfo.Directory.getDefaultInstance()) return this;
        if (other.hasDirName()) {
          bitField0_ |= 0x00000001;
          dirName_ = other.dirName_;
          onChanged();
        }
        if (other.hasTimeStamp()) {
          bitField0_ |= 0x00000002;
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (dirListBuilder_ == null) {
          if (!other.dirList_.isEmpty()) {
            if (dirList_.isEmpty()) {
              dirList_ = other.dirList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureDirListIsMutable();
              dirList_.addAll(other.dirList_);
            }
            onChanged();
          }
        } else {
          if (!other.dirList_.isEmpty()) {
            if (dirListBuilder_.isEmpty()) {
              dirListBuilder_.dispose();
              dirListBuilder_ = null;
              dirList_ = other.dirList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              dirListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDirListFieldBuilder() : null;
            } else {
              dirListBuilder_.addAllMessages(other.dirList_);
            }
          }
        }
        if (fileListBuilder_ == null) {
          if (!other.fileList_.isEmpty()) {
            if (fileList_.isEmpty()) {
              fileList_ = other.fileList_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureFileListIsMutable();
              fileList_.addAll(other.fileList_);
            }
            onChanged();
          }
        } else {
          if (!other.fileList_.isEmpty()) {
            if (fileListBuilder_.isEmpty()) {
              fileListBuilder_.dispose();
              fileListBuilder_ = null;
              fileList_ = other.fileList_;
              bitField0_ = (bitField0_ & ~0x00000008);
              fileListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFileListFieldBuilder() : null;
            } else {
              fileListBuilder_.addAllMessages(other.fileList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDirName()) {
          return false;
        }
        for (int i = 0; i < getDirListCount(); i++) {
          if (!getDirList(i).isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getFileListCount(); i++) {
          if (!getFileList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.elements.DirectoryInfo.Directory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.elements.DirectoryInfo.Directory) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object dirName_ = "";
      /**
       * <code>required string dirName = 1;</code>
       */
      public boolean hasDirName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string dirName = 1;</code>
       */
      public java.lang.String getDirName() {
        java.lang.Object ref = dirName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dirName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dirName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDirNameBytes() {
        java.lang.Object ref = dirName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dirName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dirName = 1;</code>
       */
      public Builder setDirName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dirName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dirName = 1;</code>
       */
      public Builder clearDirName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dirName_ = getDefaultInstance().getDirName();
        onChanged();
        return this;
      }
      /**
       * <code>required string dirName = 1;</code>
       */
      public Builder setDirNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dirName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timeStamp_ = "";
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public java.lang.String getTimeStamp() {
        java.lang.Object ref = timeStamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timeStamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        java.lang.Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public Builder setTimeStamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string timeStamp = 2;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.example.elements.DirectoryInfo.Directory> dirList_ =
        java.util.Collections.emptyList();
      private void ensureDirListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          dirList_ = new java.util.ArrayList<com.example.elements.DirectoryInfo.Directory>(dirList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.elements.DirectoryInfo.Directory, com.example.elements.DirectoryInfo.Directory.Builder, com.example.elements.DirectoryInfo.DirectoryOrBuilder> dirListBuilder_;

      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public java.util.List<com.example.elements.DirectoryInfo.Directory> getDirListList() {
        if (dirListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dirList_);
        } else {
          return dirListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public int getDirListCount() {
        if (dirListBuilder_ == null) {
          return dirList_.size();
        } else {
          return dirListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public com.example.elements.DirectoryInfo.Directory getDirList(int index) {
        if (dirListBuilder_ == null) {
          return dirList_.get(index);
        } else {
          return dirListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public Builder setDirList(
          int index, com.example.elements.DirectoryInfo.Directory value) {
        if (dirListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDirListIsMutable();
          dirList_.set(index, value);
          onChanged();
        } else {
          dirListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public Builder setDirList(
          int index, com.example.elements.DirectoryInfo.Directory.Builder builderForValue) {
        if (dirListBuilder_ == null) {
          ensureDirListIsMutable();
          dirList_.set(index, builderForValue.build());
          onChanged();
        } else {
          dirListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public Builder addDirList(com.example.elements.DirectoryInfo.Directory value) {
        if (dirListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDirListIsMutable();
          dirList_.add(value);
          onChanged();
        } else {
          dirListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public Builder addDirList(
          int index, com.example.elements.DirectoryInfo.Directory value) {
        if (dirListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDirListIsMutable();
          dirList_.add(index, value);
          onChanged();
        } else {
          dirListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public Builder addDirList(
          com.example.elements.DirectoryInfo.Directory.Builder builderForValue) {
        if (dirListBuilder_ == null) {
          ensureDirListIsMutable();
          dirList_.add(builderForValue.build());
          onChanged();
        } else {
          dirListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public Builder addDirList(
          int index, com.example.elements.DirectoryInfo.Directory.Builder builderForValue) {
        if (dirListBuilder_ == null) {
          ensureDirListIsMutable();
          dirList_.add(index, builderForValue.build());
          onChanged();
        } else {
          dirListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public Builder addAllDirList(
          java.lang.Iterable<? extends com.example.elements.DirectoryInfo.Directory> values) {
        if (dirListBuilder_ == null) {
          ensureDirListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dirList_);
          onChanged();
        } else {
          dirListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public Builder clearDirList() {
        if (dirListBuilder_ == null) {
          dirList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          dirListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public Builder removeDirList(int index) {
        if (dirListBuilder_ == null) {
          ensureDirListIsMutable();
          dirList_.remove(index);
          onChanged();
        } else {
          dirListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public com.example.elements.DirectoryInfo.Directory.Builder getDirListBuilder(
          int index) {
        return getDirListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public com.example.elements.DirectoryInfo.DirectoryOrBuilder getDirListOrBuilder(
          int index) {
        if (dirListBuilder_ == null) {
          return dirList_.get(index);  } else {
          return dirListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public java.util.List<? extends com.example.elements.DirectoryInfo.DirectoryOrBuilder> 
           getDirListOrBuilderList() {
        if (dirListBuilder_ != null) {
          return dirListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dirList_);
        }
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public com.example.elements.DirectoryInfo.Directory.Builder addDirListBuilder() {
        return getDirListFieldBuilder().addBuilder(
            com.example.elements.DirectoryInfo.Directory.getDefaultInstance());
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public com.example.elements.DirectoryInfo.Directory.Builder addDirListBuilder(
          int index) {
        return getDirListFieldBuilder().addBuilder(
            index, com.example.elements.DirectoryInfo.Directory.getDefaultInstance());
      }
      /**
       * <code>repeated .HDFS.Directory dirList = 3;</code>
       */
      public java.util.List<com.example.elements.DirectoryInfo.Directory.Builder> 
           getDirListBuilderList() {
        return getDirListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.elements.DirectoryInfo.Directory, com.example.elements.DirectoryInfo.Directory.Builder, com.example.elements.DirectoryInfo.DirectoryOrBuilder> 
          getDirListFieldBuilder() {
        if (dirListBuilder_ == null) {
          dirListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.elements.DirectoryInfo.Directory, com.example.elements.DirectoryInfo.Directory.Builder, com.example.elements.DirectoryInfo.DirectoryOrBuilder>(
                  dirList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          dirList_ = null;
        }
        return dirListBuilder_;
      }

      private java.util.List<com.example.elements.DirectoryInfo.File> fileList_ =
        java.util.Collections.emptyList();
      private void ensureFileListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          fileList_ = new java.util.ArrayList<com.example.elements.DirectoryInfo.File>(fileList_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.elements.DirectoryInfo.File, com.example.elements.DirectoryInfo.File.Builder, com.example.elements.DirectoryInfo.FileOrBuilder> fileListBuilder_;

      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public java.util.List<com.example.elements.DirectoryInfo.File> getFileListList() {
        if (fileListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fileList_);
        } else {
          return fileListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public int getFileListCount() {
        if (fileListBuilder_ == null) {
          return fileList_.size();
        } else {
          return fileListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public com.example.elements.DirectoryInfo.File getFileList(int index) {
        if (fileListBuilder_ == null) {
          return fileList_.get(index);
        } else {
          return fileListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public Builder setFileList(
          int index, com.example.elements.DirectoryInfo.File value) {
        if (fileListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileListIsMutable();
          fileList_.set(index, value);
          onChanged();
        } else {
          fileListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public Builder setFileList(
          int index, com.example.elements.DirectoryInfo.File.Builder builderForValue) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          fileList_.set(index, builderForValue.build());
          onChanged();
        } else {
          fileListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public Builder addFileList(com.example.elements.DirectoryInfo.File value) {
        if (fileListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileListIsMutable();
          fileList_.add(value);
          onChanged();
        } else {
          fileListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public Builder addFileList(
          int index, com.example.elements.DirectoryInfo.File value) {
        if (fileListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileListIsMutable();
          fileList_.add(index, value);
          onChanged();
        } else {
          fileListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public Builder addFileList(
          com.example.elements.DirectoryInfo.File.Builder builderForValue) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          fileList_.add(builderForValue.build());
          onChanged();
        } else {
          fileListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public Builder addFileList(
          int index, com.example.elements.DirectoryInfo.File.Builder builderForValue) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          fileList_.add(index, builderForValue.build());
          onChanged();
        } else {
          fileListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public Builder addAllFileList(
          java.lang.Iterable<? extends com.example.elements.DirectoryInfo.File> values) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fileList_);
          onChanged();
        } else {
          fileListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public Builder clearFileList() {
        if (fileListBuilder_ == null) {
          fileList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          fileListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public Builder removeFileList(int index) {
        if (fileListBuilder_ == null) {
          ensureFileListIsMutable();
          fileList_.remove(index);
          onChanged();
        } else {
          fileListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public com.example.elements.DirectoryInfo.File.Builder getFileListBuilder(
          int index) {
        return getFileListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public com.example.elements.DirectoryInfo.FileOrBuilder getFileListOrBuilder(
          int index) {
        if (fileListBuilder_ == null) {
          return fileList_.get(index);  } else {
          return fileListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public java.util.List<? extends com.example.elements.DirectoryInfo.FileOrBuilder> 
           getFileListOrBuilderList() {
        if (fileListBuilder_ != null) {
          return fileListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fileList_);
        }
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public com.example.elements.DirectoryInfo.File.Builder addFileListBuilder() {
        return getFileListFieldBuilder().addBuilder(
            com.example.elements.DirectoryInfo.File.getDefaultInstance());
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public com.example.elements.DirectoryInfo.File.Builder addFileListBuilder(
          int index) {
        return getFileListFieldBuilder().addBuilder(
            index, com.example.elements.DirectoryInfo.File.getDefaultInstance());
      }
      /**
       * <code>repeated .HDFS.File fileList = 4;</code>
       */
      public java.util.List<com.example.elements.DirectoryInfo.File.Builder> 
           getFileListBuilderList() {
        return getFileListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.elements.DirectoryInfo.File, com.example.elements.DirectoryInfo.File.Builder, com.example.elements.DirectoryInfo.FileOrBuilder> 
          getFileListFieldBuilder() {
        if (fileListBuilder_ == null) {
          fileListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.elements.DirectoryInfo.File, com.example.elements.DirectoryInfo.File.Builder, com.example.elements.DirectoryInfo.FileOrBuilder>(
                  fileList_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          fileList_ = null;
        }
        return fileListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HDFS.Directory)
    }

    // @@protoc_insertion_point(class_scope:HDFS.Directory)
    private static final com.example.elements.DirectoryInfo.Directory DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.elements.DirectoryInfo.Directory();
    }

    public static com.example.elements.DirectoryInfo.Directory getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Directory>
        PARSER = new com.google.protobuf.AbstractParser<Directory>() {
      public Directory parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Directory(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Directory> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Directory> getParserForType() {
      return PARSER;
    }

    public com.example.elements.DirectoryInfo.Directory getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HDFS_File_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HDFS_File_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HDFS_Directory_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HDFS_Directory_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Directory.proto\022\004HDFS\"9\n\004File\022\020\n\010fileN" +
      "ame\030\001 \002(\t\022\021\n\ttimeStamp\030\002 \001(\t\022\014\n\004size\030\003 \001" +
      "(\005\"o\n\tDirectory\022\017\n\007dirName\030\001 \002(\t\022\021\n\ttime" +
      "Stamp\030\002 \001(\t\022 \n\007dirList\030\003 \003(\0132\017.HDFS.Dire" +
      "ctory\022\034\n\010fileList\030\004 \003(\0132\n.HDFS.FileB%\n\024c" +
      "om.example.elementsB\rDirectoryInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HDFS_File_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HDFS_File_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HDFS_File_descriptor,
        new java.lang.String[] { "FileName", "TimeStamp", "Size", });
    internal_static_HDFS_Directory_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HDFS_Directory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HDFS_Directory_descriptor,
        new java.lang.String[] { "DirName", "TimeStamp", "DirList", "FileList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
