// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BlockReport.proto

package com.example.report;

public final class BlockReport {
  private BlockReport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockReportRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HDFS.BlockReportRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>repeated int32 blockList = 2;</code>
     */
    java.util.List<java.lang.Integer> getBlockListList();
    /**
     * <code>repeated int32 blockList = 2;</code>
     */
    int getBlockListCount();
    /**
     * <code>repeated int32 blockList = 2;</code>
     */
    int getBlockList(int index);
  }
  /**
   * Protobuf type {@code HDFS.BlockReportRequest}
   */
  public  static final class BlockReportRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HDFS.BlockReportRequest)
      BlockReportRequestOrBuilder {
    // Use BlockReportRequest.newBuilder() to construct.
    private BlockReportRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockReportRequest() {
      id_ = 0;
      blockList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockReportRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                blockList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              blockList_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                blockList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                blockList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          blockList_ = java.util.Collections.unmodifiableList(blockList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.report.BlockReport.internal_static_HDFS_BlockReportRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.report.BlockReport.internal_static_HDFS_BlockReportRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.report.BlockReport.BlockReportRequest.class, com.example.report.BlockReport.BlockReportRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int BLOCKLIST_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> blockList_;
    /**
     * <code>repeated int32 blockList = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getBlockListList() {
      return blockList_;
    }
    /**
     * <code>repeated int32 blockList = 2;</code>
     */
    public int getBlockListCount() {
      return blockList_.size();
    }
    /**
     * <code>repeated int32 blockList = 2;</code>
     */
    public int getBlockList(int index) {
      return blockList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < blockList_.size(); i++) {
        output.writeInt32(2, blockList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < blockList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(blockList_.get(i));
        }
        size += dataSize;
        size += 1 * getBlockListList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.report.BlockReport.BlockReportRequest)) {
        return super.equals(obj);
      }
      com.example.report.BlockReport.BlockReportRequest other = (com.example.report.BlockReport.BlockReportRequest) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && getBlockListList()
          .equals(other.getBlockListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (getBlockListCount() > 0) {
        hash = (37 * hash) + BLOCKLIST_FIELD_NUMBER;
        hash = (53 * hash) + getBlockListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.report.BlockReport.BlockReportRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.report.BlockReport.BlockReportRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.report.BlockReport.BlockReportRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HDFS.BlockReportRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HDFS.BlockReportRequest)
        com.example.report.BlockReport.BlockReportRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.report.BlockReport.internal_static_HDFS_BlockReportRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.report.BlockReport.internal_static_HDFS_BlockReportRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.report.BlockReport.BlockReportRequest.class, com.example.report.BlockReport.BlockReportRequest.Builder.class);
      }

      // Construct using com.example.report.BlockReport.BlockReportRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        blockList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.report.BlockReport.internal_static_HDFS_BlockReportRequest_descriptor;
      }

      public com.example.report.BlockReport.BlockReportRequest getDefaultInstanceForType() {
        return com.example.report.BlockReport.BlockReportRequest.getDefaultInstance();
      }

      public com.example.report.BlockReport.BlockReportRequest build() {
        com.example.report.BlockReport.BlockReportRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.report.BlockReport.BlockReportRequest buildPartial() {
        com.example.report.BlockReport.BlockReportRequest result = new com.example.report.BlockReport.BlockReportRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          blockList_ = java.util.Collections.unmodifiableList(blockList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.blockList_ = blockList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.report.BlockReport.BlockReportRequest) {
          return mergeFrom((com.example.report.BlockReport.BlockReportRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.report.BlockReport.BlockReportRequest other) {
        if (other == com.example.report.BlockReport.BlockReportRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.blockList_.isEmpty()) {
          if (blockList_.isEmpty()) {
            blockList_ = other.blockList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBlockListIsMutable();
            blockList_.addAll(other.blockList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.report.BlockReport.BlockReportRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.report.BlockReport.BlockReportRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> blockList_ = java.util.Collections.emptyList();
      private void ensureBlockListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          blockList_ = new java.util.ArrayList<java.lang.Integer>(blockList_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 blockList = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getBlockListList() {
        return java.util.Collections.unmodifiableList(blockList_);
      }
      /**
       * <code>repeated int32 blockList = 2;</code>
       */
      public int getBlockListCount() {
        return blockList_.size();
      }
      /**
       * <code>repeated int32 blockList = 2;</code>
       */
      public int getBlockList(int index) {
        return blockList_.get(index);
      }
      /**
       * <code>repeated int32 blockList = 2;</code>
       */
      public Builder setBlockList(
          int index, int value) {
        ensureBlockListIsMutable();
        blockList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 blockList = 2;</code>
       */
      public Builder addBlockList(int value) {
        ensureBlockListIsMutable();
        blockList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 blockList = 2;</code>
       */
      public Builder addAllBlockList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureBlockListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blockList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 blockList = 2;</code>
       */
      public Builder clearBlockList() {
        blockList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HDFS.BlockReportRequest)
    }

    // @@protoc_insertion_point(class_scope:HDFS.BlockReportRequest)
    private static final com.example.report.BlockReport.BlockReportRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.report.BlockReport.BlockReportRequest();
    }

    public static com.example.report.BlockReport.BlockReportRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BlockReportRequest>
        PARSER = new com.google.protobuf.AbstractParser<BlockReportRequest>() {
      public BlockReportRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlockReportRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockReportRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockReportRequest> getParserForType() {
      return PARSER;
    }

    public com.example.report.BlockReport.BlockReportRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BlockReportResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HDFS.BlockReportResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool toDelete = 1;</code>
     */
    boolean hasToDelete();
    /**
     * <code>required bool toDelete = 1;</code>
     */
    boolean getToDelete();

    /**
     * <code>required bool toRestore = 2;</code>
     */
    boolean hasToRestore();
    /**
     * <code>required bool toRestore = 2;</code>
     */
    boolean getToRestore();

    /**
     * <code>repeated int32 blockList = 3;</code>
     */
    java.util.List<java.lang.Integer> getBlockListList();
    /**
     * <code>repeated int32 blockList = 3;</code>
     */
    int getBlockListCount();
    /**
     * <code>repeated int32 blockList = 3;</code>
     */
    int getBlockList(int index);

    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    java.util.List<com.example.elements.BlockInfo.Block> 
        getBlocksList();
    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    com.example.elements.BlockInfo.Block getBlocks(int index);
    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    int getBlocksCount();
    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    java.util.List<? extends com.example.elements.BlockInfo.BlockOrBuilder> 
        getBlocksOrBuilderList();
    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    com.example.elements.BlockInfo.BlockOrBuilder getBlocksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HDFS.BlockReportResponse}
   */
  public  static final class BlockReportResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HDFS.BlockReportResponse)
      BlockReportResponseOrBuilder {
    // Use BlockReportResponse.newBuilder() to construct.
    private BlockReportResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockReportResponse() {
      toDelete_ = false;
      toRestore_ = false;
      blockList_ = java.util.Collections.emptyList();
      blocks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockReportResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              toDelete_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              toRestore_ = input.readBool();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                blockList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              blockList_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                blockList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                blockList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                blocks_ = new java.util.ArrayList<com.example.elements.BlockInfo.Block>();
                mutable_bitField0_ |= 0x00000008;
              }
              blocks_.add(
                  input.readMessage(com.example.elements.BlockInfo.Block.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          blockList_ = java.util.Collections.unmodifiableList(blockList_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          blocks_ = java.util.Collections.unmodifiableList(blocks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.report.BlockReport.internal_static_HDFS_BlockReportResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.report.BlockReport.internal_static_HDFS_BlockReportResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.report.BlockReport.BlockReportResponse.class, com.example.report.BlockReport.BlockReportResponse.Builder.class);
    }

    private int bitField0_;
    public static final int TODELETE_FIELD_NUMBER = 1;
    private boolean toDelete_;
    /**
     * <code>required bool toDelete = 1;</code>
     */
    public boolean hasToDelete() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool toDelete = 1;</code>
     */
    public boolean getToDelete() {
      return toDelete_;
    }

    public static final int TORESTORE_FIELD_NUMBER = 2;
    private boolean toRestore_;
    /**
     * <code>required bool toRestore = 2;</code>
     */
    public boolean hasToRestore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool toRestore = 2;</code>
     */
    public boolean getToRestore() {
      return toRestore_;
    }

    public static final int BLOCKLIST_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> blockList_;
    /**
     * <code>repeated int32 blockList = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getBlockListList() {
      return blockList_;
    }
    /**
     * <code>repeated int32 blockList = 3;</code>
     */
    public int getBlockListCount() {
      return blockList_.size();
    }
    /**
     * <code>repeated int32 blockList = 3;</code>
     */
    public int getBlockList(int index) {
      return blockList_.get(index);
    }

    public static final int BLOCKS_FIELD_NUMBER = 4;
    private java.util.List<com.example.elements.BlockInfo.Block> blocks_;
    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    public java.util.List<com.example.elements.BlockInfo.Block> getBlocksList() {
      return blocks_;
    }
    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    public java.util.List<? extends com.example.elements.BlockInfo.BlockOrBuilder> 
        getBlocksOrBuilderList() {
      return blocks_;
    }
    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    public int getBlocksCount() {
      return blocks_.size();
    }
    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    public com.example.elements.BlockInfo.Block getBlocks(int index) {
      return blocks_.get(index);
    }
    /**
     * <code>repeated .HDFS.Block blocks = 4;</code>
     */
    public com.example.elements.BlockInfo.BlockOrBuilder getBlocksOrBuilder(
        int index) {
      return blocks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasToDelete()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToRestore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBlocksCount(); i++) {
        if (!getBlocks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, toDelete_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, toRestore_);
      }
      for (int i = 0; i < blockList_.size(); i++) {
        output.writeInt32(3, blockList_.get(i));
      }
      for (int i = 0; i < blocks_.size(); i++) {
        output.writeMessage(4, blocks_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, toDelete_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, toRestore_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < blockList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(blockList_.get(i));
        }
        size += dataSize;
        size += 1 * getBlockListList().size();
      }
      for (int i = 0; i < blocks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, blocks_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.report.BlockReport.BlockReportResponse)) {
        return super.equals(obj);
      }
      com.example.report.BlockReport.BlockReportResponse other = (com.example.report.BlockReport.BlockReportResponse) obj;

      boolean result = true;
      result = result && (hasToDelete() == other.hasToDelete());
      if (hasToDelete()) {
        result = result && (getToDelete()
            == other.getToDelete());
      }
      result = result && (hasToRestore() == other.hasToRestore());
      if (hasToRestore()) {
        result = result && (getToRestore()
            == other.getToRestore());
      }
      result = result && getBlockListList()
          .equals(other.getBlockListList());
      result = result && getBlocksList()
          .equals(other.getBlocksList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasToDelete()) {
        hash = (37 * hash) + TODELETE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getToDelete());
      }
      if (hasToRestore()) {
        hash = (37 * hash) + TORESTORE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getToRestore());
      }
      if (getBlockListCount() > 0) {
        hash = (37 * hash) + BLOCKLIST_FIELD_NUMBER;
        hash = (53 * hash) + getBlockListList().hashCode();
      }
      if (getBlocksCount() > 0) {
        hash = (37 * hash) + BLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getBlocksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.report.BlockReport.BlockReportResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.report.BlockReport.BlockReportResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.report.BlockReport.BlockReportResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HDFS.BlockReportResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HDFS.BlockReportResponse)
        com.example.report.BlockReport.BlockReportResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.report.BlockReport.internal_static_HDFS_BlockReportResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.report.BlockReport.internal_static_HDFS_BlockReportResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.report.BlockReport.BlockReportResponse.class, com.example.report.BlockReport.BlockReportResponse.Builder.class);
      }

      // Construct using com.example.report.BlockReport.BlockReportResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBlocksFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        toDelete_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        toRestore_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        blockList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          blocksBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.report.BlockReport.internal_static_HDFS_BlockReportResponse_descriptor;
      }

      public com.example.report.BlockReport.BlockReportResponse getDefaultInstanceForType() {
        return com.example.report.BlockReport.BlockReportResponse.getDefaultInstance();
      }

      public com.example.report.BlockReport.BlockReportResponse build() {
        com.example.report.BlockReport.BlockReportResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.report.BlockReport.BlockReportResponse buildPartial() {
        com.example.report.BlockReport.BlockReportResponse result = new com.example.report.BlockReport.BlockReportResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.toDelete_ = toDelete_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toRestore_ = toRestore_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          blockList_ = java.util.Collections.unmodifiableList(blockList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.blockList_ = blockList_;
        if (blocksBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            blocks_ = java.util.Collections.unmodifiableList(blocks_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.blocks_ = blocks_;
        } else {
          result.blocks_ = blocksBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.report.BlockReport.BlockReportResponse) {
          return mergeFrom((com.example.report.BlockReport.BlockReportResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.report.BlockReport.BlockReportResponse other) {
        if (other == com.example.report.BlockReport.BlockReportResponse.getDefaultInstance()) return this;
        if (other.hasToDelete()) {
          setToDelete(other.getToDelete());
        }
        if (other.hasToRestore()) {
          setToRestore(other.getToRestore());
        }
        if (!other.blockList_.isEmpty()) {
          if (blockList_.isEmpty()) {
            blockList_ = other.blockList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBlockListIsMutable();
            blockList_.addAll(other.blockList_);
          }
          onChanged();
        }
        if (blocksBuilder_ == null) {
          if (!other.blocks_.isEmpty()) {
            if (blocks_.isEmpty()) {
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureBlocksIsMutable();
              blocks_.addAll(other.blocks_);
            }
            onChanged();
          }
        } else {
          if (!other.blocks_.isEmpty()) {
            if (blocksBuilder_.isEmpty()) {
              blocksBuilder_.dispose();
              blocksBuilder_ = null;
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000008);
              blocksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBlocksFieldBuilder() : null;
            } else {
              blocksBuilder_.addAllMessages(other.blocks_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToDelete()) {
          return false;
        }
        if (!hasToRestore()) {
          return false;
        }
        for (int i = 0; i < getBlocksCount(); i++) {
          if (!getBlocks(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.report.BlockReport.BlockReportResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.report.BlockReport.BlockReportResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean toDelete_ ;
      /**
       * <code>required bool toDelete = 1;</code>
       */
      public boolean hasToDelete() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool toDelete = 1;</code>
       */
      public boolean getToDelete() {
        return toDelete_;
      }
      /**
       * <code>required bool toDelete = 1;</code>
       */
      public Builder setToDelete(boolean value) {
        bitField0_ |= 0x00000001;
        toDelete_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool toDelete = 1;</code>
       */
      public Builder clearToDelete() {
        bitField0_ = (bitField0_ & ~0x00000001);
        toDelete_ = false;
        onChanged();
        return this;
      }

      private boolean toRestore_ ;
      /**
       * <code>required bool toRestore = 2;</code>
       */
      public boolean hasToRestore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool toRestore = 2;</code>
       */
      public boolean getToRestore() {
        return toRestore_;
      }
      /**
       * <code>required bool toRestore = 2;</code>
       */
      public Builder setToRestore(boolean value) {
        bitField0_ |= 0x00000002;
        toRestore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool toRestore = 2;</code>
       */
      public Builder clearToRestore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toRestore_ = false;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> blockList_ = java.util.Collections.emptyList();
      private void ensureBlockListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          blockList_ = new java.util.ArrayList<java.lang.Integer>(blockList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 blockList = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getBlockListList() {
        return java.util.Collections.unmodifiableList(blockList_);
      }
      /**
       * <code>repeated int32 blockList = 3;</code>
       */
      public int getBlockListCount() {
        return blockList_.size();
      }
      /**
       * <code>repeated int32 blockList = 3;</code>
       */
      public int getBlockList(int index) {
        return blockList_.get(index);
      }
      /**
       * <code>repeated int32 blockList = 3;</code>
       */
      public Builder setBlockList(
          int index, int value) {
        ensureBlockListIsMutable();
        blockList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 blockList = 3;</code>
       */
      public Builder addBlockList(int value) {
        ensureBlockListIsMutable();
        blockList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 blockList = 3;</code>
       */
      public Builder addAllBlockList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureBlockListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blockList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 blockList = 3;</code>
       */
      public Builder clearBlockList() {
        blockList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.util.List<com.example.elements.BlockInfo.Block> blocks_ =
        java.util.Collections.emptyList();
      private void ensureBlocksIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          blocks_ = new java.util.ArrayList<com.example.elements.BlockInfo.Block>(blocks_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.elements.BlockInfo.Block, com.example.elements.BlockInfo.Block.Builder, com.example.elements.BlockInfo.BlockOrBuilder> blocksBuilder_;

      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public java.util.List<com.example.elements.BlockInfo.Block> getBlocksList() {
        if (blocksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(blocks_);
        } else {
          return blocksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public int getBlocksCount() {
        if (blocksBuilder_ == null) {
          return blocks_.size();
        } else {
          return blocksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public com.example.elements.BlockInfo.Block getBlocks(int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);
        } else {
          return blocksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public Builder setBlocks(
          int index, com.example.elements.BlockInfo.Block value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.set(index, value);
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public Builder setBlocks(
          int index, com.example.elements.BlockInfo.Block.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.set(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public Builder addBlocks(com.example.elements.BlockInfo.Block value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public Builder addBlocks(
          int index, com.example.elements.BlockInfo.Block value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(index, value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public Builder addBlocks(
          com.example.elements.BlockInfo.Block.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public Builder addBlocks(
          int index, com.example.elements.BlockInfo.Block.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public Builder addAllBlocks(
          java.lang.Iterable<? extends com.example.elements.BlockInfo.Block> values) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, blocks_);
          onChanged();
        } else {
          blocksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public Builder clearBlocks() {
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          blocksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public Builder removeBlocks(int index) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.remove(index);
          onChanged();
        } else {
          blocksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public com.example.elements.BlockInfo.Block.Builder getBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public com.example.elements.BlockInfo.BlockOrBuilder getBlocksOrBuilder(
          int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);  } else {
          return blocksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public java.util.List<? extends com.example.elements.BlockInfo.BlockOrBuilder> 
           getBlocksOrBuilderList() {
        if (blocksBuilder_ != null) {
          return blocksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(blocks_);
        }
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public com.example.elements.BlockInfo.Block.Builder addBlocksBuilder() {
        return getBlocksFieldBuilder().addBuilder(
            com.example.elements.BlockInfo.Block.getDefaultInstance());
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public com.example.elements.BlockInfo.Block.Builder addBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().addBuilder(
            index, com.example.elements.BlockInfo.Block.getDefaultInstance());
      }
      /**
       * <code>repeated .HDFS.Block blocks = 4;</code>
       */
      public java.util.List<com.example.elements.BlockInfo.Block.Builder> 
           getBlocksBuilderList() {
        return getBlocksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.elements.BlockInfo.Block, com.example.elements.BlockInfo.Block.Builder, com.example.elements.BlockInfo.BlockOrBuilder> 
          getBlocksFieldBuilder() {
        if (blocksBuilder_ == null) {
          blocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.elements.BlockInfo.Block, com.example.elements.BlockInfo.Block.Builder, com.example.elements.BlockInfo.BlockOrBuilder>(
                  blocks_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          blocks_ = null;
        }
        return blocksBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HDFS.BlockReportResponse)
    }

    // @@protoc_insertion_point(class_scope:HDFS.BlockReportResponse)
    private static final com.example.report.BlockReport.BlockReportResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.report.BlockReport.BlockReportResponse();
    }

    public static com.example.report.BlockReport.BlockReportResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BlockReportResponse>
        PARSER = new com.google.protobuf.AbstractParser<BlockReportResponse>() {
      public BlockReportResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlockReportResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockReportResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockReportResponse> getParserForType() {
      return PARSER;
    }

    public com.example.report.BlockReport.BlockReportResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HDFS_BlockReportRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HDFS_BlockReportRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HDFS_BlockReportResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HDFS_BlockReportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BlockReport.proto\022\004HDFS\032\013Block.proto\"3" +
      "\n\022BlockReportRequest\022\n\n\002id\030\001 \002(\005\022\021\n\tbloc" +
      "kList\030\002 \003(\005\"j\n\023BlockReportResponse\022\020\n\010to" +
      "Delete\030\001 \002(\010\022\021\n\ttoRestore\030\002 \002(\010\022\021\n\tblock" +
      "List\030\003 \003(\005\022\033\n\006blocks\030\004 \003(\0132\013.HDFS.BlockB" +
      "!\n\022com.example.reportB\013BlockReport"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.elements.BlockInfo.getDescriptor(),
        }, assigner);
    internal_static_HDFS_BlockReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HDFS_BlockReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HDFS_BlockReportRequest_descriptor,
        new java.lang.String[] { "Id", "BlockList", });
    internal_static_HDFS_BlockReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HDFS_BlockReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HDFS_BlockReportResponse_descriptor,
        new java.lang.String[] { "ToDelete", "ToRestore", "BlockList", "Blocks", });
    com.example.elements.BlockInfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
